ExperimentWeb/Controllers/AngularController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExperimentWeb.Controllers
{
    public class AngularController : Controller
    {
        // GET: Angular
        public ActionResult Index()
        {
            return View();
        }
    }
}

ExperimentWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExperimentWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ExperimentWeb/Controllers/LeafletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExperimentWeb.Controllers
{
    public class LeafletController : Controller
    {
        // GET: Leaflet
        public ActionResult Index()
        {
            return View();
        }
    }
}

ExperimentWeb/Controllers/ReactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExperimentWeb.Models;
using Newtonsoft.Json;

namespace ExperimentWeb.Controllers
{
    public class ReactController : Controller
    {
        // GET: React
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateComment(Comment comment)
        {
            // parse the comments object
            var path = Server.MapPath("~/data.json");
            var curCommentList = JsonConvert.DeserializeObject<List<Comment>>(System.IO.File.ReadAllText(path));
            curCommentList.Add(comment);
            var newContent = JsonConvert.SerializeObject(curCommentList);
            System.IO.File.WriteAllText(path, newContent);
            return Content(newContent, "application/json");
        }

        public ActionResult MyExample1()
        {
            return View();
        }

        public ActionResult ReactEcosystemCheck()
        {
            return View();
        }
    }
}

ExperimentWeb/Controllers/RedisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExperimentWeb.Controllers
{
    public class RedisController : Controller
    {
        // GET: Redis
        public ActionResult Index()
        {
            Session["data"] = "data";
            return View();
        }
    }
}

ExperimentWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ExperimentWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ExperimentWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <h2>Laboratory</h2>
        <p>
            This is a list of client-side and server-side technologies that I am exploring.
        </p>

        <h3>Technologies:</h3>
        <ul>
            <li><a href="@Url.Action("Index", "MassTransit")">Broker Messaging MassTransit and RabbitMQ</a></li>
            <li><a href="@Url.Action("Index", "SignalRTest")">SignalR Test</a></li>
            <li><a href="@Url.Action("Index", "Redis")">Redis Session State Provider Test</a></li>
            <li><a href="@Url.Action("Index", "Angular")">Angular 2.0</a></li>
            <li><a href="@Url.Action("Index", "TypeScript")">TypeScript</a></li>
            <li>
                React JS
                <ul>
                    <li><a href="@Url.Action("Index", "React")">ReactJS official tutorial example complete implementation.</a></li>
                    <li><a href="@Url.Action("MyExample1", "React")">Personal Labs to explore the capability of React.</a></li>
                    <li><a href="@Url.Action("ReactEcosystemCheck", "React")">Testing of React ecosystem for routing and Flux architecture.</a></li>
                </ul>
            </li>
            
            <li><a href="@Url.Action("Index", "Knockout")">Knockout JS</a></li>
            <li><a href="@Url.Action("Index", "Leaflet")">Leaflet</a></li>
            <li>Underscore</li>
        </ul>

        <p>
            <a href="@Url.Action("Index", "Library")">This page lists the libraries which I am using in Production projects.</a>
        </p>
    </div>
</div>